# Generated by Django 4.0.5 on 2022-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
